### ISSUE TITLE
does it work on IOS? (detox-getprops library might not be compatible with this version of Detox)

### ISSUE THREAD

**Issue by danielzzz** [plaa/detox-getprops#3]
when I try to use it on ios, I am getting this error:

```
Could not parse exception message. detox-getprops library might not be compatible with this version of Detox.

    Message:
    Test Failed: Failed expectation: TOHAVETEXT(text == “_unfoundable_text”) WITH MATCHER(identifier: == “wantsNewsBtn”)
    TIP: To print view hierarchy on failed actions/matches, use loglevel verbose and above.

      at parseMessage (../node_modules/detox-getprops/index.js:48:9)
      at getProps (../node_modules/detox-getprops/index.js:12:12)
```

detox --version
17.4.3

as there is getAttributes on ios, is this intended to be used on Android only?

thanks, cheers, dan

**Comment by plaa** [comment]
Drats.  Since approx Detox 16.8.2 the [exceptions don't contain the view hierarchy information](https://github.com/wix/Detox/commit/2f7ac6664c567a64d1b494e4b15051c6cc9edc1e) unless the log level is set to verbose. This means that the hack that detox-getprops relies upon doesn't work.

Could you @danielzzz  try running detox with `--loglevel verbose` or `--loglevel trace` and test whether it works with it?

**Comment by danielzzz** [comment]
hello, 
it's not working for me, even with --loglevel verbose or trace..
bummer..
thanks anyway!
dan

it seems it's coming: https://github.com/wix/Detox/pull/2098

**Comment by sudheer54900** [comment]
Hello,
I am also facing this issue with Detox 19.4.2 , on Android also, any Fix or work around ?

**Comment by radhakrishnanakireddy** [comment]
I am also facing the same issue on IOS 19.5.7
